version: "3.9"
services:
  app:
    container_name: powertofly
    image: powertofly
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql+psycopg2://root:postgres@database:5432/power_to_fly
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
      - POSTGRES_DB=power_to_fly
    volumes:
      - db_volume:/var/lib/postgresql

  web:
    build: .
    environment:
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
  cache:
    image: redis
    container_name: redis
    environment:
      - CACHE_TYPE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_DB=0
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=500
    volumes:
      - redis_data:/data

volumes:
  db_volume:
  redis_data: