version: "3.9"
services:
  app:
    container_name: powertofly
    image: powertofly
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/power_to_fly
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=power_to_fly
    volumes:
      - db_volume:/var/lib/postgresql

  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"

volumes:
  db_volume: